services:
  minio:
    image: docker.io/bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=robert
      - MINIO_ROOT_PASSWORD=robertisawesome
      - MINIO_DEFAULT_BUCKETS=robert

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
