[package]
name = "workload"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
common = {path = "../common"}
bytes = "1.6.0"
serde = { version = "1.0.203", features = ["derive"] }
clap = { version = "4.5.7", features = ["derive"] }
serde_json = "1.0.117"
